spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:aladdinbiyabangerd@gmail.com}
    password: ${MAIL_PASSWORD:lgwc ajdp xxjj cyuq}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true