spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:updevic.onlinecourse@gmail.com}
    password: ${MAIL_PASSWORD:ukzu nvrf ojni hldk}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mailjet:
  apikey: ${API_KEY_MAILJET}
  secretkey: ${SECRET_KEY_MAILJET}