stripe:
  secret:
    key: ${STRIPE_SECRET}

application:
  security:
    jwt:
      expiration: 86400000
      key: ${SECURITY_KEY}

ALGORITHM: ${ALGORITHM}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

frontend:
  url1: ${FRONTEND_URL1}
  url2: ${FRONTEND_URL2}

server:
  port: ${PORT:8080}
  tomcat:
    uri-encoding: utf-8